# Generated by Django 3.0.6 on 2020-06-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('YFI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_no', models.PositiveSmallIntegerField(null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='')),
                ('bio', models.TextField(null=True)),
            ],
        ),
    ]
