# Generated by Django 3.0.6 on 2020-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YFI', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='download_1.png', null=True, upload_to=''),
        ),
    ]
