# Generated by Django 3.0.6 on 2020-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YFI', '0004_templates_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
